### ISSUE TITLE
Give zoning information as optional paramter to type building functions

### ISSUE THREAD

**Issue by mlauster** [RWTH-EBC/TEASER#141]
I thin we can easily make our type building process more flexible by adding the zoning information (what for zones with what for a share of area and waht usage) as an optional parameter in the function header. We can define our actual values as default.
In this way, a user can easily overwrite this information with his own without the need of implementing his own function. I think in most cases users just want to change this information and not the actual calculation of wall ares etc.

**Comment by PRemmen** [comment]
I think as we are getting to the point of integrating more than one archetype function (e.g. Tabula) we should stick to the current workflow (changing the class attribute and running archetype calculation again). closed for that reason
