### ISSUE TITLE
Gui Envelopes area 

### ISSUE THREAD

**Issue by yGoerguelue** [RWTH-EBC/TEASER#148]
If we change the area of an envelope and press the save everthing works fine. But if we change the area first and then the orientation to another existing envelope with the same orientation and press the save button. The area value, before we changed it, will be added to the envelope. 

Bug is already fixed in controller, but is comment out. After issue  #143 is solved, we can reimplement it.

**Comment by PRemmen** [comment]
This will be fixed in #143
