### ISSUE TITLE
Edit Building Button has no Effect

### ISSUE THREAD

**Issue by MichaMans** [RWTH-EBC/TEASER#161]
Edit building button and the change of building parameters has no effect to the current building. 

We have multiple options to implement a functionality here.
1. No effect (we can leave everything like it is, and delete the edit building button and make the fields editable)
2. recalculate the current building

**Comment by PRemmen** [comment]
I vote for option 2, lets raise a warning somewhere, that old values will be overwritten.

**Comment by PRemmen** [comment]
- change Edit Building to "Delete Building" Button
- make textboxes on the left side editable and raise warning: 
  - This has no effect on your building parameters, its just general information.
  - Three buttons: Okay, Cancel, Update Archetype Building (only appears if bldg is an archetypebuilding)

**Comment by MichaMans** [comment]
Merged with #288
