### ISSUE TITLE
Path of boundary conditions

### ISSUE THREAD

**Issue by mlauster** [RWTH-EBC/TEASER#190]
In the path of boundary conditions (T_set, etc.), we have a redundant slash in the worng direction. It doesn't seem to bother Dymola, but looks ugly

![unbenanntes bild](https://cloud.githubusercontent.com/assets/6892690/14168093/326405f6-f720-11e5-822a-e891e1dff98c.png)

**Comment by MichaMans** [comment]
This should be solved with PR #263
