### ISSUE TITLE
Revise the infiltration rate

### ISSUE THREAD

**Issue by MichaMans** [RWTH-EBC/TEASER#193]
Currently we are using the infiltration rate in the thermal zone class not as an export parameter for the AixLib models. We should change this. Therefore we need to make sure that the tz infiltration rate is exported as the baseACH parameter in the records.

**Comment by PRemmen** [comment]
Do base_ach in boundary conditions and infiltration rate have the same meaning? In this case I just would make sure that if boundary conditions are set both attributes have the same value and then change baseACH to infiltration rate in the AixLib Template.

**Comment by HenrykWolisz** [comment]
Trying to parametrize a model with teaser I've faced exactly that problem. The infiltration rate setting is not passed to the building record. @MichaMans, I would be very thankful if you could have a look at this issue!

**Comment by PRemmen** [comment]
Could you write a small code snippet how you try to change the infiltration rate? @HenrykWolisz

**Comment by HenrykWolisz** [comment]
After generating a zone in teaser --> "Zone Details" --> "Static Heat Load" --> "Infiltration Rate"
Changing that "Infiltration Rate" value however does not change the "baseACH" value in the building record and therefore the changed "Infiltration Rate" is ignored in the simulation. @MichaMans @PRemmen

**Comment by PRemmen** [comment]
There are two solutions to that:

1. You can change code of mainui.py line 2478 to 
```python
self.current_zone.use_conditions.base_ach = self.infiltration_rate_line_edit.text()
```
2. You can change code of export in output/modelicatemplate/AixLib/AixLib_zone line 59 to:
```
baseACH = ${zone.infiltration_rate}
```

As already mentioned above, these are redundant values. This redundancy will be deleted in next version of TEASER see #347
