### ISSUE TITLE
Bug in example singlebuilding

### ISSUE THREAD

**Issue by MichaMans** [RWTH-EBC/TEASER#239]
There is a bug in the example file where we are trying to call prj.save_gml. This function does not exist. We should change this to prj.save_project.

**Comment by PRemmen** [comment]
Shortly after release we already got some feedback with things to revise, lets collect this stuff in one branch and merge it:

- Revise READMEs to directly link to the documentation and update how to install teaser
- Revise the singlebuilding.py example as we already got some feedback, that it might not be enough to understand how to create a building from scatch (also in the docs)
- We got some unused API function and one import module was not an API function
- Docstrings of project.py was not up to date

all issues have been solved in docsOpen

@MichaMans

**Comment by PRemmen** [comment]
To install teaser via pip we need to adjust the setup file, we can do this in the release 0.3.1 togehter with the things mentioned above

**Comment by MichaMans** [comment]
merged with PR #240
