### ISSUE TITLE
example file: example_createbuilding.py >> buildingphysics - missing imports & bug

### ISSUE THREAD

**Issue by R33B** [RWTH-EBC/TEASER#251]
The following imports were missing (Python 2.7):

```
from teaser.logic.buildingobjects.buildingphysics.rooftop import Rooftop
from teaser.logic.buildingobjects.buildingphysics.layer import Layer
from teaser.logic.buildingobjects.buildingphysics.material import Material
from teaser.logic.buildingobjects.buildingphysics.outerwall import OuterWall
from teaser.logic.buildingobjects.buildingphysics.innerwall import InnerWall
from teaser.logic.buildingobjects.buildingphysics.window import Window
from teaser.logic.buildingobjects.buildingphysics.groundfloor import GroundFloor
```

**Comment by R33B** [comment]
after having fixed the import issue with the lines as mentioned above, i get the following ERROR:

```
  File "...\Anaconda2\lib\site-packages\teaser\data\output\citygml_output.py", line 160, in _set_gml_building
    teaser_building.height_of_floors)

TypeError: unsupported operand type(s) for *: 'NoneType' and 'NoneType'
```

**Comment by MichaMans** [comment]
Hi,
thanks for your report. At the moment, i can't reproduce your issue(s) with anaconda under windows. 
To improve our support, we need more information how and where your error occures. I assume you installed teaser by using `pip install teaser`. After that works teaser should be installed properly. To check this, you can use `pip show teaser`. For the use of our examples, you need to execute the singlebuilding.py (for example) with python (`python singlebuilding.py`). Does this work for you? How did you fix your imports and are you working under windows or unix?

**Comment by R33B** [comment]
Hi, 
I installed teaser as you described, `pip show teaser`, `pip show pyxb` , `pip show mako` , `pip show pytest` show that all packages are installed.

I executed example_createbuilding.py in Spyder 2.3.8, with Python 2.7. 
I engineered the code from the text in the example section: 

> http://pythonhosted.org/teaser/teaser.Examples.html

I noticed that the imports as mentioned above were missing, so that `OuterWall()`, `Material()`, etc. were unknown. 
After having added the necessary imports, i get the second error.

Thank you for your support
Robin 
[example_createbuilding.zip](https://github.com/RWTH-EBC/TEASER/files/313565/example_createbuilding.zip)

**Comment by R33B** [comment]
PS: So actually the problem accurs in the last lines of the file:
`prj.save_citygml(
    file_name="ExampleProject",
    path=None)`

**Comment by MichaMans** [comment]
Ok, so for the moment i think there is a bug in the citygml output (or better, we don't support "not fully defined buildings"). What i mean with fully defined buildings is, that we are using the height of floors, the number of floors and the net leased area of a building as a kind of basic and always set parameters. So you can, to solve your error, either set these building parameters in your example (recommended, then the export should work too), or don't use the city_gml export function. I hope you can get this work with these 2 options and we'll discuss how we can solve this in a sustainable way.

For the other issue with the missing import you are kind of right, we missed to adjust the name of the example. The example your are using is the singlebuilding.py example, where all necessary imports should be shown. (We'll change this in the docu)

**Comment by R33B** [comment]
Allright, thank you for the explanation about citygml.

Perfect, the import issue was no big deal, but less experienced users might be pretty confused if even the example does not work.

The issue can be closed.

**Comment by MichaMans** [comment]
Ok, I'm glad to help you. Don't hesitate to contact us with other improvements, bugs or general thoughts.
