### ISSUE TITLE
missing within statements for OpenModelica

### ISSUE THREAD

**Issue by mlauster** [RWTH-EBC/TEASER#254]
openModelica needs for each .mo-file a header line stating to which package the file belongs (excluding top-level models or packages). For all sub-level package.mo-files and model.mo-files, we need to add `within XXX`, `XXX` being the entire path from the top-level, e.g. `within Project.Random.Random_DataBase`. package.mo-files are within the upper-level package, so package.mo for `Random`-package needs `within Project`, while `Random.mo` (a model in the `Random-package`) needs `within Project.Random`. And delimit line with `;`.

**Comment by R33B** [comment]
Thank you very much, this works.

Can you already estimate, when there will be an update of TEASER which automatically writes those "within" - lines?

**Comment by mlauster** [comment]
Hopefully within the next weeks, but I can't give you an exact date.

**Comment by R33B** [comment]
Ok, thanks.

**Comment by MichaMans** [comment]
This should be solved with PR #263
