### ISSUE TITLE
calling calc_all_buildings without parameter

### ISSUE THREAD

**Issue by mlauster** [RWTH-EBC/TEASER#255]
In our new release, we set `used_library_calc`, `number_of_elements` and `merge_windows_calc`. However, when calling `calc_all_buildings`, one need to give the attributes as parameter again:

![unbenanntes bild](https://cloud.githubusercontent.com/assets/6892690/16079418/cdddcb92-3303-11e6-9f09-db8299456bf9.png)

We should decide for one way.

**Comment by MichaMans** [comment]
This should be solved with PR #263
