### ISSUE TITLE
TEASER is incompatible with Unix-like operating systems

### ISSUE THREAD

**Issue by yfuerst** [RWTH-EBC/TEASER#260]
TEASER declares paths with double backslashes ("\\"), which is Windows specific. Unix-like systems use forward slashes ("/") and need no escape sequence. I am therefore unable to execute TEASER on my Linux machine.
`os` is clever and works out which slashes you need for your OS. A better way, than providing the slashes yourself, would be the use of `os.path.join`. Other solutions could be the use of raw strings or forward slashes, which will be substituted by Python with the correct slashes, according to the OS.

**Comment by PRemmen** [comment]
@yfuerst  thanks for raising that issue. We are aware of this bug ( #181 and #214 ) and hope to resolve that issue soon. I can't promise exactly when, but we will keep you in touch.

**Comment by MichaMans** [comment]
This should be solved with PR #263

**Comment by PRemmen** [comment]
@yfuerst the latest release 0.3.6 should solve this issue. Please update you teaser distribution by using pip. If you find any problems, please reopen this issue :-)

**Comment by yfuerst** [comment]
I just pulled from git and the issue seems to be solved. Thanks for the fast action.
