### ISSUE TITLE
Updating .xsd schemas with version numbers

### ISSUE THREAD

**Issue by mlauster** [RWTH-EBC/TEASER#268]
Our xsd schemas defining our teaserXML files etc. have currently no version number. That makes it hard to update them and keep track of old versions. This topic came up with #253, as fixing a typo in the xsd schema breaks backward compatibility if do not support loading old files as well. This is only possible if we check with which xsd version a file has been created and have binding classes for all versions accordingly. To handle this, we propose:

- [x] Every xsd schema gets a version number. As we hopefully don't need to change them that often, we can aggregate some files to one version number.
- [x] We keep only the xsd schema of the current version.
- [x] We create a new directory structure with one directory per version.
- [x] We keep the binding classes for all versions in their corresponding directory.

**Comment by mlauster** [comment]
I did some research regarding best practice in xsd versioning and - surprisingly - we are not the first ones touching this issue. This is quite a nice source:
[Versioning.pdf](https://github.com/RWTH-EBC/TEASER/files/378002/Versioning.pdf)
On my current knowledge, I would vote for option 2b, adding a version number to the xsd and an xsd element so that every instances needs to state to which schema version(s) it is valid. This would require some pre-parsing when loading the xml instances to check the version number, load the appropriate xsd version and then validate the file. But actually I don't see another way of doing that. The document mentions some stuff about changing namespaces but it is not clear to me for what we would need to do this.
To conclude: we need to do some fundamental, non-backwards compatible changes (in the sense of loading teaserXML files and boundary conditions-xml and archetype-xml) that I would first like to discuss and come to the best solution.

**Comment by PRemmen** [comment]
@mlauster I would like to change our data structure a little bit (see #306 #305 #304) Would this be a good idea to push this issue at the same time?

**Comment by mlauster** [comment]
Today decided to go for option 2b. That means, adding a root attribute to the xsd-schema that contains the version number. From that on, every xml-file has a version number linking to it's xsd-schema and thus as well to it's binding. We then pre-parse the xml-file to read to version number using xml-tree or likewise. In case that pre-parsing is time-consuming, we first try the actual binding and if that fails pre-parse and choose the corresponding binding.

**Comment by mlauster** [comment]
@PRemmen , let's solve all this in one step before committing to `master`or `development`.

**Comment by PRemmen** [comment]
i think this work is done, will raise PR
