### ISSUE TITLE
PEP 0008 

### ISSUE THREAD

**Issue by PRemmen** [RWTH-EBC/TEASER#29]
Not all of our code is PEP 0008 compliant. Eclipse, Spyder and PyDev are all able to analyse the code according to pep 0008. We should try to be as compliant as possible

**Comment by PRemmen** [comment]
before releasing v0.4.0 @mlauster will check code for pep8 compliance

**Comment by pema1** [comment]
Sorry for that posting but this talk by Raymond Hettinger at PyCon 2015 on PEP8 is awesome:
Beyond PEP 8 -- Best practices for beautiful intelligible code
https://youtu.be/wf-BqAjZb8M

**Comment by PRemmen** [comment]
merged with #328 code should be more or less pep8 compliant
