### ISSUE TITLE
Link Type Elements and MAterial

### ISSUE THREAD

**Issue by PRemmen** [RWTH-EBC/TEASER#305]
The Definition of Type Elements should be changed in a way that only the material name is stored in the TypeBuildingElements.xml and the loader should use this name to load the corresponding material from MaterialTempalte.xml.

This issue is realted to #304

**Comment by PRemmen** [comment]
The following has been done (see branch issue305_XML):

- link typeelements.xml with material.xml by giving both an attribute called material_id
- adjust the loader of Material and BuildingElement

The following need to be done:

- revise both XML (see #304 #306)
- adjust saver of Material and BuildingElement

**Comment by MichaMans** [comment]
merged with #317
