### ISSUE TITLE
Bug in set all construction window 

### ISSUE THREAD

**Issue by yGoerguelue** [RWTH-EBC/TEASER#314]
![bug](https://cloud.githubusercontent.com/assets/15320756/18829096/084e0d3c-83db-11e6-9489-083af065dd53.PNG)

**Comment by MichaMans** [comment]
@yGoerguelue could you give us more information about the bug you've found? I have no idea when and why this bug occures.

**Comment by yGoerguelue** [comment]
When the bug occurs.
After adding a layer and pressing the save button in "Set all construction" window.

Why the bug occurs.
We don't have a layer attribute called position and when i tried to execute the save button i get the AttributeError. The correct attribute is id.
