### ISSUE TITLE
warnings in GUI

### ISSUE THREAD

**Issue by PRemmen** [RWTH-EBC/TEASER#332]
The GUI tries to display warnings, errors, etc. but if an warning or error occurs before the GUI is fully initialized this makes python crash.

simple solution: put these three lines of code at the end of mainui.MainUI().**init**()

``` python

        # Used to display the console inside the program.
        sys.stdout = EmittingStream(textWritten=self.normal_output_written)
        sys.stdin = EmittingStream(textWritten=self.normal_output_written)
        sys.stderr = EmittingStream(textWritten=self.normal_output_written)
```

This will display all warnings during initialization in regular Python console

This issue was found by @HenrykWolisz

**Comment by MichaMans** [comment]
Solved with PR #335
