### ISSUE TITLE
wrong values for alphas

### ISSUE THREAD

**Issue by mlauster** [RWTH-EBC/TEASER#337]
For `AixLib` exports, the indoor coefficient of heat transfer for interior walls (`alphaiwi`) is always set to zero. Oddly, it seems to work for `Annex60`. 
For all indoor alphas, the value is set to convective plus radiative (so e.g. 7.7 instead of 2.7), although even in the `AixLib` models, we handle radiative and convective heat transfer in separate circuits.
@PRemmen, can you help to track down the bug, it seems to be quite urgent as this affects all models and leads to wrong results.

**Comment by mlauster** [comment]
Okay, I think I found both. The second one (alphas conv + rad) is already fixed in the above mentioned branch.
For the other one (`alphaiwi`=0), I guess inconsistent naming in thermalzone.py. Line 916-918 say

self.alpha_conv_iw = 1/(self.r_conv_inner_iw * self.area_iw)
self.alpha_rad_iw = 1/(self.r_rad_inner_iw * self.area_iw)
self.alpha_comb_iw = 1/(self.r_comb_inner_iw * self.area_iw)

But in the init 136-138, the parameters are named (adding `_inner`):

self.alpha_conv_inner_iw = 0.0
self.alpha_rad_inner_iw = 0.0
self.alpha_comb_inner_iw = 0.0

PyCharm consequently marks Line 916-918 complaining about class attributes defined outside of init. Shall we rename Line 916-918? 

Is there something else to check or could this be solved?

**Comment by mlauster** [comment]
I added my solution to branch `issue337_alphas`.

**Comment by PRemmen** [comment]
Please also change the names in `tests.test_data.py` then it should be ready for merge (don't forget to increase version numbers :+1: ) as this is a bug fix

**Comment by mlauster** [comment]
Okay, I found three more bugs, mainly related to Annex-Templates. 
- The outdoor heat transfer coefficient was added to `RRem`.
- The convective and radiative heat transfer coefficients for roof elements in singlebuildings.py were interchanged
- The ground floor area was not added to exterior walls for two-elements model

Should be all fixed now
