### ISSUE TITLE
Revise default value of solar absorption

### ISSUE THREAD

**Issue by mlauster** [RWTH-EBC/TEASER#344]
We currently set a default value of 0.7, I guess out of the validation case of VDI 6007-1. We always use this default value when relying on archetypes. According to
http://www.ziegel.de/cgi-bin/tamzserver.exe/phpamz?id=505
this value relates to a red brick wall. The source defines also values for other materials. Maybe we should take a mean value as default value or set solar absorption in our materials.xml.

![unbenanntes bild](https://cloud.githubusercontent.com/assets/6892690/20714341/02327df4-b64c-11e6-890e-3ac1e1455a37.png)

**Comment by PRemmen** [comment]
@mlauster i added first values for solar abs and added solar_absorption and emissivity to material loader. Do you have more sources for such properties? Could you maybe extend materials.xml for those materials?

**Comment by mlauster** [comment]
Unfortunately not, it seems heavily dependent on the surface' color.

**Comment by PRemmen** [comment]
so how to proceed?
