### ISSUE TITLE
Restructure ThermalZone class (especially calculation)

### ISSUE THREAD

**Issue by PRemmen** [RWTH-EBC/TEASER#347]
Currently the ThermalZone class is rather large holds lots of functions and attributes that are not needed for standard case (e.g. all calculation attributes for four-element model). The idea is to separate the calculation of the parameters from the ThermalZone by creating four new classes (one for each model) and saving functions and attributes related to the calculation method in that class. This class will then be attached to the ThermalZone with an attribute.

We could also extend the lists for outer, inner walls to alls possible type (e.g. list for outer_walls, ground_floors and rooftops).

**The API of thermal zone, building, and project class should not change**

**Comment by PRemmen** [comment]
It might make sense to also restructure the building class in the same manner (to have AixLib and Annex classes, because we have specific attributes (e.g. pathes for internal gains). Any objections that this will be done in the same branch?

**Comment by mlauster** [comment]
No, go for it

**Comment by mlauster** [comment]
Another item to solve within this branch: We currently follow the definition of attributes according to VDI 6007. Unfortunately, these definitions are in some parts specific to the VDI calculations. E.g. `r_rest` contains the outdoor coefficient of radiative and convective heat transfer `alpha_comb_outer_ow`. For the Annex and AixLib models, we need the resistance (let's name it r_rem) separate to heat transfer coefficients. Thus, we substract `alpha_comb_outer_ow` from `r_rest` in the templates. We should find an own definition and descriptive names within TEASER that represent the smallest parts we need and avoid post-processing in templates. Regarding resistances and capacitances, I suggest to have two lists for resistances and capacitances each and one resistance separate that is the one between exterior surface and capacitance `r_remaining`. This one ensures a valid U-value.

**Comment by PRemmen** [comment]
done in #349, stays open until release

**Comment by PRemmen** [comment]
done and merge in #365 stays open until released
