### ISSUE TITLE
Export of boundary conditions for Annex and AixLib thermal zone models

### ISSUE THREAD

**Issue by mlauster** [RWTH-EBC/TEASER#352]
We currently export boundary conditions only for `AixLib.Multizone`. We should add them as well to `Annex60` models and `AixLib.ThermalZone`. For this, we need to split them for one file per zone and move the related functions from `logic.simulation` to `output.modelicatemplate.XXX_output` as we need to know which model is used. This information is so far not available for functions in `logic.simulation`  and according to #347 will be organized per model.

**Comment by PRemmen** [comment]
done in #349, stays open until release

**Comment by PRemmen** [comment]
still needs some adjustment for annex models
