### ISSUE TITLE
Check export of orientation of buildings

### ISSUE THREAD

**Issue by mlauster** [RWTH-EBC/TEASER#353]
A short test showed that buildings with the `AixLib` and the `Annex60` weather model seemed to be oriented differently (west and east orientations are switched) . As we typically export rectangular buildings, this has no impact on the results of typical buildings. However, I could only investigate the entries, resp. the positions of the entries within the vector of orientations. I should set up a buildings with different areas directing east and west and then see if this is really a bug or not.

**Comment by PRemmen** [comment]
#349

**Comment by PRemmen** [comment]
done in #349, stays open until release

**Comment by JSchiefelbein** [comment]
Might be relevant for #395 (orientations and angles in weather class of VDI 6007 core)
