### ISSUE TITLE
update unit tests for release 0.5

### ISSUE THREAD

**Issue by PRemmen** [RWTH-EBC/TEASER#373]

**Comment by MichaMans** [comment]
Unittests are working again, i'll make a PR for Release05.

In addtition we should add additional tests for the missing calculation cores

**Comment by MichaMans** [comment]
We should imporve the pytests for the upcoming release. Therefore i'll start a list of things we should test here:

- [ ] citygml_input (Load CityGML file)
- [ ] urbanrenet archetypebuildings modules
- [ ] material_output (Save a material)
- [ ] boundcond_output (Save boundary conditions)
- [ ] buildingelement_output (Save BE)
- [ ] guistart.py (Wether leaving out of the test, or testing startup?)
- [ ] API / project should be covered by 100%

**Comment by PRemmen** [comment]
lets include issues #345 and #346 in this branch

**Comment by PRemmen** [comment]
I vote for not supporting GUI at all

**Comment by mlauster** [comment]
Leaving GUI out of testing is fine for me

**Comment by PRemmen** [comment]
it's quite cumbersome to test old bindings as we would need to provide old and not recommended files within teaser to test it. Do we really want this?

**Comment by PRemmen** [comment]
Actually i just recognized that we have old files in teaser.examples.examplefiles created with 0.4 should we transfer these to verison 0.5 or use them for unit testing (i vote for transfer)

**Comment by MichaMans** [comment]
I Vote for Transfer. We should keep the examples up to date with the current bindings.
