### ISSUE TITLE
Bug in example - e6_generate_building

### ISSUE THREAD

**Issue by ThomasSchuetz** [RWTH-EBC/TEASER#385]
Index error when assigning windows' values:

win_dict = {"Window_east": [5.0, 90.0, 90.0],
                "Window_south": [8.0, 90.0, 180.0],
                "Window_west": [5.0, 90.0, 270.0]}

    for key, value in win_dict.items():

        win = Window(parent = tz)
        win.name = key
        win.area = value[1]
        win.tilt = value[2]
        win.orientation = value[3]

This should be changed to 
        win.area = value[0]
        win.tilt = value[1]
        win.orientation = value[2]

**Comment by ThomasSchuetz** [comment]
This should be solved with bb40ea5c33f6a18ce7d0ad3b6416826b511b2b48

**Comment by PRemmen** [comment]
@ThomasSchuetz thanks

there is also an index error in groundfloor, i will fix that and make a pull request into dev

**Comment by MichaMans** [comment]
Solved with PR #386
