### ISSUE TITLE
Missing attributes in UseConditions.XML

### ISSUE THREAD

**Issue by PRemmen** [RWTH-EBC/TEASER#388]
Some attributes for use conditions are not set in XML and default values are always taken from BoundaryConditions python class. This is not convenient and user friendly. 

Solution: set all attributes in XML to default values, this will not change primary simulation results, but the user has the opportunity to manually change values if wanted.

reported by @TobiasBlacha

**Comment by TobiasBlacha** [comment]
was merged with #389
