### ISSUE TITLE
Add reference for retrofit values (such as u-values)

### ISSUE THREAD

**Issue by JSchiefelbein** [RWTH-EBC/TEASER#393]
Currently, a suitable reference for retrofit values is missing. Should be added

**Comment by JSchiefelbein** [comment]
Related to #391

**Comment by MichaMans** [comment]
We should definitely add the WSVO / EnEv as reference. I checked the values, they look all fine except of the Groundfloor U value from 2014 or younger. This should be 0.30.

**Comment by PRemmen** [comment]
solved with latest release v0.5.0
