### ISSUE TITLE
Extract house dict data out of TEASER

### ISSUE THREAD

**Issue by JSchiefelbein** [RWTH-EBC/TEASER#396]
Currently, houseData dict got some hard coded values. These values should be extracted from TEASER typebuildings / thermal_zones. 
(vdi_6007_simulation.py)

**Comment by MichaMans** [comment]
Maybe we should collect all to dos in the VDI Simulation Integration Issue for a clear overview #297

**Comment by PRemmen** [comment]
closed as suggested by @MichaMans we use one issue to track progress
