### ISSUE TITLE
Integrate MASEA data base into MaterialTemplates

### ISSUE THREAD

**Issue by jsc-tbe** [RWTH-EBC/TEASER#404]
To get a consistent MaterialTemplates.xml file with the most commonly used materials in the building sector, it was decided (@PRemmen, @MichaMans) to use the MASEA data base ("Materialdatensammlung für die energetische Altbausanierung", see link below) and to import the values into a new MaterialTemplates.xml file. Therefore the old materials will be replaced and the TypeBuildingElements.xml file has to be adapted to the new materials.

[http://www.masea-ensan.de/](url)

**Comment by PRemmen** [comment]
@jsc-tbe if working on this issue please consider integrating #412

**Comment by mlauster** [comment]
Is there any work going on here or is planned, @jsc-tbe, @PRemmen?

**Comment by jsc-tbe** [comment]
As the MASEA DB is integrated (currently used in development branch) I think we can close this issue.
