### ISSUE TITLE
AixLib Templates CoolerOn

### ISSUE THREAD

**Issue by PRemmen** [RWTH-EBC/TEASER#438]
This issue relates to #376 

### What is our Problem?

- The ideal cooler for AixLib models is hardcoded to be always switched off

### Why do we want to solve it?

- to get ideal cooling power for buildings (however, we need to be careful with results as e.g. we use dry air)

### How do we want to solve it?

- Adding a placeholder in all AixLib templates referencing an attribute in the Calculation module
- Adding simplified cooling load calculation in calculation modules

**Comment by PRemmen** [comment]
We need two more variables in TEASER

1. decide if heater is turned on ort not (boolean)
2. temperature set "back" for cooler (float) - probably different from heater (much higher)

**Comment by MichaMans** [comment]
Do you suggest both in the useconditions?

**Comment by PRemmen** [comment]
yes I think it is probably the best place for this. this would then also be relevant for #510

**Comment by PRemmen** [comment]
We have to be very careful with set temperatures for heating and cooling. In  a first approach I implemented it wrong (higher desired temperatures in the day for cooling). However, If we apply it correct it will interfer with the heating temperature, thus we need to make sure that cooling temperature is always at least 0,5 K above heating temperature.
