### ISSUE TITLE
Winpython (v.3.6.1) & numpy: error and solution

### ISSUE THREAD

**Issue by MarcusVogt** [RWTH-EBC/TEASER#442]
## What is the problem? 

Winpython (v.3.6.1, 64 bit) might cause problems using numpy and you may get an error message regarding a missing "numpy-mkl". This error could be produced by an automatic update process of numpy while installing teaser with pip under Windows. 

## How to solve it?

After installation of teaser install "numpy‑1.12.1+mkl‑cp36‑cp36m‑win_amd64.whl" using pip from here: 
http://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy
Now the error should be fixed.  
You´ll find further information to this topic here: 
http://stackoverflow.com/questions/37267399/importerror-cannot-import-name-numpy-mkl

@PRemmen @mlauster

**Comment by PRemmen** [comment]
@MarcusVogt thanks for this issue.

I think it might be worth it to integrate something like a FAQ section in the docs. As this is not really a bug in TEASER but more a problem installing pre-compiled binaries under windows with pip.
