### ISSUE TITLE
Does the building type 'school' already exist?

### ISSUE THREAD

**Issue by lma18** [RWTH-EBC/TEASER#451]
I need to simulate a school in Dymola. Does a school already exist as a building type?
@PRemmen , @mlauster

**Comment by PRemmen** [comment]
@lma18 This archetype building does not exist. If you do not have some kind of statistical archetype information of schools you could do a workaround (I strongly advise to check if this approach is applicable for you purpose).

The regular office building exists of following usage zones:

- Office (50% of net leased area)
- Floor (25% of net leased area)
- Storage (15% of net leased area)
- Meeting (4% of net leased area)
- Restroom (4% of net leased area)
- ICT (2% of net leased area)

Maybe a first good guess is to change the usage zone `Office` to `Class room (school), group room (kindergarden)` . This will affect the internal wall calculation and the use conditions (suchs as usage time, and internal gains). You can also adapt other zones if you find that the usage zones should be different.

To do this code the following steps:

1. Instantiate an office building (using function `add_non_residential` from `Project` class.
2. Change the `Office` class attribute `zone_area_factors` (its a dict)
   - replace the entry `{"Office": [0.5, "Group Office (between 2 and 6 employees)"]` to `{"ClassRoom": [0.5, "Class room (school), group room (kindergarden)"]`
3. run `Office` class function `generate_archetype`
4. run building parameter calculation using `calc_all_buildings` from `Project` class.

Good luck :-).
