### ISSUE TITLE
Add German KfW building standards to TEASER

### ISSUE THREAD

**Issue by JSchiefelbein** [RWTH-EBC/TEASER#453]
Currently, TEASER does not account for KfW building standards. Thus, KfW buildings have to be modeled manually. We should find a better solution to integrate the KfW standard.

**Comment by PRemmen** [comment]
Have a look at http://webtool.building-typology.eu/#bd and check wether one of these construction types helps, which we are going to implement into TEASER very soon. In addition, to my understanding KFW refers to a maximum primary energy consumption and maximal transmission heat loss, which both would be depend on a.) energy conversion system b.) architecture (at least ratio between window/outerwalls/roof/ground floor) and not to a certain minimal thickness of e.g. insulation layer. Please correct me if I am worng :-) @JSchiefelbein

**Comment by JSchiefelbein** [comment]
@PRemmen Yes, you are right. KfW typology "mixes up" building physics and energy conversion. However,
it would be great to have an extraction of building physics / its representation in TEASER, for instance based on KfW projects or existing buildings.

**Comment by PRemmen** [comment]
Best solution I can think of right now is implementing a certain function that computes `H_t'` according to EnEv standard compare this to the desired `H_t'`and then adapt insultion of outer elements so it fits KFW (70,55, ...) needs (you would need to come up with some rule that decides what to insulate first and to what extend, as KFW does not prescribe that to my knowledge)

**Comment by mlauster** [comment]
Alternatively, one could have a look for existing KfW buildings and assume that they have a typical construction for that type.

**Comment by mlauster** [comment]
This issue is on hold since there is no progress and it does not seem to speed up in the next time.
