### ISSUE TITLE
Overestimation of space heating demands for current German building standards

### ISSUE THREAD

**Issue by JSchiefelbein** [RWTH-EBC/TEASER#460]
@SeRemy mentioned an overestimation of space heating demands for up-to-date German building standards (e.g. current EnEV) for VDi 6007 thermal simulation. 

I ran two simulations with TEASER VDI 6007 core (#297):
- TEASER typebuilding with 2014 as year of construction
- TEASER typebuilding with 1980 as year of construction and 2014 as year of modernization

The first run led to an overestimation of the annual space heating demand:

`Sum of heating energy in kWh:
20204
Spec. net space heating energy in kWh/m2:
101`

![1](https://user-images.githubusercontent.com/8487502/26867917-68e0c24e-4b67-11e7-8d1e-d9e04a4f0c43.jpg)

However, the retrofiting within run nb. 2 led to results, which were closer to the current EnEV:
`Sum of heating energy in kWh:
9155
Spec. net space heating energy in kWh/m2:
45`

![2](https://user-images.githubusercontent.com/8487502/26868100-0ffc174a-4b68-11e7-8f10-c52f442d2c0d.png)

Seems like the retrofiting is working, but we got an issue with the current standard in TEASER.

**Comment by JSchiefelbein** [comment]
Attached the BuildingExtended inputs:
`extended_building = build_ex.BuildingExtended(environment,
                                                  build_year=build_year,
                                                  mod_year=mod_year,
                                                  build_type=0,
                                                  roof_usabl_pv_area=30,
                                                  net_floor_area=200,
                                                  height_of_floors=2.8,
                                                  nb_of_floors=2,
                                                  neighbour_buildings=0,
                                                  residential_layout=0,
                                                  attic=1, cellar=1,
                                                  construction_type='heavy',
                                                  dormer=1)`

**Comment by PRemmen** [comment]
This is due to the fact, that we do not have the whole EnEv standard as type elements. You will recognize, that the last construction period is from 1995-2015 which is very long. 

As mentioned, we are working on getting Tabula into TEASER, with this you will have the opportunity to generate more distinct type buildings for recent year (see #439)
