### ISSUE TITLE
TEASER compatibility with Python versions

### ISSUE THREAD

**Issue by Malhotra-e3d** [RWTH-EBC/TEASER#464]
## What is the problem?
-As of now in the "How to use TEASER/Dependencies", it is stated that TEASER is compatible with 2.7<=python>=3.3.  

## Why do we want to solve it?
- Would be beneficial to have a description stating the compatibility with the latest versions.

**Comment by PRemmen** [comment]
Actually >= 3.3 means that is should be compatible with versions 3.3 3.4 3.5 and 3.6. 

However, we can rephrase the readme...

**Comment by Malhotra-e3d** [comment]
Alright. Thanks @PRemmen

**Comment by PRemmen** [comment]
Solved  in development branch, will go into master with the next version (probably in 2 or 3 weeks)
