### ISSUE TITLE
Add useful return statements to the api/project class

### ISSUE THREAD

**Issue by MichaMans** [RWTH-EBC/TEASER#471]
## What is the problem?

At TEASER's current state of development we do not serve any return statements. I don't know if this is really a problem but it might be useful to serve some return statements like the used path or something. I think this is a feature we can discuss here

## Why do we want to solve it?

Return statements like the used path might be helpful for using the api within other applications.

## How do we want to solve it?

We add useful return statements to the project class

In addition we should integrate a delete function in utilities which helps us to delete all files currently in the standard directory or in the path

**Comment by PRemmen** [comment]
not at all!

**Comment by mlauster** [comment]
@MichaMans, what is the current status on that? Seems to be in progress for quite some time, maybe we could merge a first part and solve all further stuff afterwards.

**Comment by MichaMans** [comment]
I'll create a PR since already implemented the path returns. Thanks for the reminder!

**Comment by PRemmen** [comment]
seems to be solved in dev
