### ISSUE TITLE
ISO-Container Archetype

### ISSUE THREAD

**Issue by mkuehnel09** [RWTH-EBC/TEASER#486]
## What is the problem?

- There is no Archetype for ISO-Containers

## Why do we want to solve it?

- In order to simulate the temperature control system for battery energy storage in an ISO-Container 20" I need a model for that container. 

## How do we want to solve it?

- In case there will be a need for similar aplications, i want to implement the model as a new archetype besides residential and nonresidential.

**Comment by PRemmen** [comment]
@mkuehnel09 thanks for the issue. You are welcome to commit your changes and request review from us. One first question is: What are typical use case(s) beside the quite specific case of a battery storage?

**Comment by PRemmen** [comment]
as I do not see any typical use case for TEASER and also no progress I'll close this
