### ISSUE TITLE
Create test for the actual release versions of the different supported modelica libraries

### ISSUE THREAD

**Issue by MichaMans** [RWTH-EBC/TEASER#491]
## What is the problem?

Supported modelica libraries are changing over time

## Why do we want to solve it?

We should support always the latest version of the libraries

## How do we want to solve it?

create a unittest which trys to import PyGithub and if it finds it, it should test for the supported versions

**Comment by mlauster** [comment]
Ouh, could there be an automated way? Using the release numbers or how does it work? This would really be a huge advantage!

**Comment by MichaMans** [comment]
solved with PR #492
