### ISSUE TITLE
Typos throughout the code

### ISSUE THREAD

**Issue by mlauster** [RWTH-EBC/TEASER#494]
## What is the problem?

- We have numerous typos and grammar mistakes throughout the code, in particular in documentation sections.

## Why do we want to solve it?

- Because that makes TEASER look more professional and helps reading the documentation.

## How do we want to solve it?

- By replace typos and mistakes with the correct spelling.

This issue serves as collecting works regarding typos. I will close it after some first corrections and the next ones can still mention this issue to have all works collected in one place.

**Comment by thorade** [comment]
Do you know this tiny Linux command line tool?
https://github.com/vlajos/misspell_fixer
Could even be added to the Travis testing...

**Comment by mlauster** [comment]
@thorade, that looks nice! I'm a bit afraid of breaking the code when renaming variables, in particular attributes of classes. This is why I'm so far sticking to manual checks.

**Comment by mlauster** [comment]
Closed as long as no further work is done.
