### ISSUE TITLE
Newbie

### ISSUE THREAD

**Issue by Stelzhammer** [RWTH-EBC/TEASER#496]
Hi, first of all thank you for the great job you are doing by developing such a tool for building simulation. While writing on my mastethesis i stumbled over teaser because i´m using the RC-Model SimpleRoomFourElements and i´m searching the right parameters for the RC-Elements (Window, Ext-Wall etc. etc.). I followed your guideline but unfortunately i can t get python to know the order git. And how can i run your program to give me the right numbers for the parameters of the convective coefficient......the resistor for the window and so on ......

**Comment by mlauster** [comment]
@Stelzhammer, this is more a question of getting Python and Teaser to run and not related to Teaser development, what we discuss in these issues. I will close it and stay in contact with you via mail.
To record the answer that might help others: If you simply would like to use Teaser without developing it, it is enough to install Teaser via PIP. Open a console and type "pip install TEASER". If Python has been installed successfully on your system, this should work. We recommend using Python >=3.4. You can then run our examples that you can find in the site-packages directory of your python installation. This will help you to learn working with Teaser. If you would like to use specific branches or participate in the development of Teaser, you need to install git, have a look on the internet for that topic or start here https://github.com/RWTH-EBC/EBC-Tutorials/tree/master/EBC-Git-101.
