### ISSUE TITLE
Parameter 'height_of_floors'

### ISSUE THREAD

**Issue by RWTHSebastian** [RWTH-EBC/TEASER#498]
## What is the problem?

- In building.py set_gml_attributes is height_of_floors = storey height (in German: Geschosshöhe) (so it is in the citygml_input.py)
![1](https://user-images.githubusercontent.com/19650702/33833372-b6077bf2-de7f-11e7-986c-2a5e02a67c53.PNG)

In thermalzone.py at function set_volume_zone the attribute height_of_floors has to be the 'room height', since self.area = NGF (in German: Nettogrundfläche and not Bruttogrundfläche)?
![2](https://user-images.githubusercontent.com/19650702/33833434-e983a460-de7f-11e7-9017-54a320daa36c.PNG)

## Why do we want to solve it?

There should be a distinction between clear room height and storey height. 
Storey height = room height + intermediate ceiling thickness

## How do we want to solve it?

Change formula for zone volume 'volume'! Deduction of the intermediate ceiling thickness from the storey height to calculate the room height, so the actual air volume of the zone is calculated: 
volume = self. area (= net_floor_area) * (self. parent. height_of_floors - h_ceiling)

**Comment by PRemmen** [comment]
@RWTHSebastian Also here you have so solution in place already 👍 perfect! A PR is very much appreciated

Could you also translate that issue in englisch?

**Comment by PRemmen** [comment]
as gml is no longer supported I'll close this issue
