### ISSUE TITLE
residential_building: attic & cellar

### ISSUE THREAD

**Issue by RWTHSebastian** [RWTH-EBC/TEASER#500]
## What is the problem?

**Attic**:
Die Heizlast sinkt um 13 %, wenn ein unbeheiztes Dach (none_heated_attic) zu einem teilweise beheiztem Dach wird. Die Heizlast sinkt um 2 %, wenn ein unbeheiztes Dach zu einem voll beheiztem Dach wird. Warum sinkt bei einem teilweise beheiztem Dach die Heizlast mehr als bei einem voll beheiztem? Warum sinkt sie überhaupt? Die Heizlast des ganzen Gebäudes müsste doch eigentlich steigen, wenn das Dach beheizt wird!
![4](https://user-images.githubusercontent.com/19650702/33834645-e6c9eb9a-de83-11e7-9747-db3e339e3d26.PNG)

**Cellar**:
Die Heizlast sinkt um 5 %, wenn ein unbeheizter Keller zu einem teilweise beheiztem Keller wird. Die Heizlast sinkt um 8 %, wenn ein unbeheizter Keller zu einem voll beheiztem Keller wird. Warum sinkt sie überhaupt? Die Heizlast des ganzen Gebäudes müsste doch eigentlich steigen, wenn der Keller beheizt wird!
![5](https://user-images.githubusercontent.com/19650702/33834649-ea341c60-de83-11e7-80ac-29fc7160ec2b.PNG)

## Why do we want to solve it?

- ...

## How do we want to solve it?

- Sind da vielleicht Fehler in den Berechnungen?

**Comment by PRemmen** [comment]
@RWTHSebastian with your provided information I am not able to track the error. Please make a new branch including a short testscript so we can follow your calculation.
