### ISSUE TITLE
non_residential_building: with_AHU = True

### ISSUE THREAD

**Issue by RWTHSebastian** [RWTH-EBC/TEASER#501]
## What is the problem?

- Bei der Simulation von Nicht-Wohn-Gebäuden mit AHU verändert sich die Heizlast nur minimal (~0,02 %) im Vergleich zu Gebäuden ohne AHU. Die Werte der Attribute PHeatAHU und PCoolAHU sind über den kompletten Simulationszeitraum konstant Null. Warum wird die Leistung der AHU nicht simuliert?

Sind Berechnungen für AHU Stand jetzt noch nicht in TEASER integriert?

## Why do we want to solve it?

- ...

## How do we want to solve it?

- ...

**Comment by PRemmen** [comment]
@RWTHSebastian I suspect this is an error in your implementation. We use simulation with AHUs all the time and it certainly makes a difference. as mentioned in #500 a testscript would help.
