### ISSUE TITLE
Probleme mit XML_save und XML_load

### ISSUE THREAD

**Issue by RWTHSebastian** [RWTH-EBC/TEASER#502]
## What is the problem?

Bisher habe ich über zwei Wege in TEASER Projekte im Outputordner erstellt:
**1.	e2_export_aixlib_models.py**
Hierbei wird die e1_generate_archetype.py ausgeführt und das Projekt erstellt (e1_generate_archetype.py->project.py->office.py …). Es wird dabei keine XML Datei erstellt.

**2.	e4_save.py und e9_XML_to_Python_Project**
Die e4_save.py erstellt eine Instanz der Klasse project unter dem Namen prj. Der Variablen prj wird anschließend der Wert e1.example_generate_archetype() zugewiesen. Genau das gleiche macht die erste Variante in der e2_export_aixlib_models.py auch. Anschließend wird das Projekt als XML mit der Funktion save_teaser_xml in dem Outputordner abgespeichert. Die e9_XML_to_Python_Project.py (neu) läd diese XML mit der Funktion load_teaser_xml unter Verwendung der e5_load.py und erstellt anschließend ein Python-Project im Outputordner.

**Problem:**

Erstellt man nun zweimal das gleiche Projekte über die erste und anschließend über die zweite Methode erhält man bei der Simulation in Dymola unterschiedliche Ergebnisse für den Jahresheizwärmebedarf (integrierte Heizlasten) (~50% Unterschied). Beide Male wird zum Abspeichern des Projekts im Outputordner die Funktion export_aixlib() verwendet. Daher scheidet diese Funktion als Fehlerquelle aus.

## Why do we want to solve it?

- ...

## How do we want to solve it?

**Mögliche Ursachen:**
- fehlerhafte Funktion zum Laden der XML Datei (teaserxml_input.py, Funktion load_teaser_xml)
- fehlerhafte Funktion zum Speichern der XML Datei (teaserxml_output.py, Funktion save_teaser_xml)

**Comment by PRemmen** [comment]
@RWTHSebastian This is in deed suspicious. I never ran into such a problem. But again, without having seen what you are doing in ` e9_XML_to_Python_Project.py` I am not able to track the error what so ever.

However, I suspect that the function `export_aixlib()` is the cause of the error. It is more likely that (if it is really a error) we have some issue with import and export of XML. If you provide more information (like the script in a branch) I will look into this. (after you translated issue in englisch ;-) )

**Comment by mlauster** [comment]
And keep in mind, these are examples that help you understand what Teaser is doing and they might be serve as a blueprint for your own scripts. But I wouldn't use them as part of your application.
