### ISSUE TITLE
Bug: BuildingElement with layer thickness of 0.0

### ISSUE THREAD

**Issue by PRemmen** [RWTH-EBC/TEASER#505]
## What is the problem?

- in `TypeBuildingElements.xml` the `OuterWall` 1995-2015 "light" has two layers with thickness of 0.0 

## Why do we want to solve it?

- it produces errors in records and thus can't be simulated

## How do we want to solve it?

- add proper thickness to the materials in XML file, before double check with older versions of TEASER to get right thickness

**Comment by MichaMans** [comment]
Maybe we should interate this with #538 ?
