### ISSUE TITLE
Clean Up UseConditions

### ISSUE THREAD

**Issue by PRemmen** [RWTH-EBC/TEASER#510]
## What is the problem?

- we drag around a lot of variables we actually do not really need for use conditions

## Why do we want to solve it?

- have it more compact and user friendly

## How do we want to solve it?

- delete all unused parameters

**Comment by PRemmen** [comment]
Special focus should be on internal gains, especially machines and persons as this is currently kind of messed up in TEASER

**Comment by MichaMans** [comment]
Some collection for discussion and or implementation:

- persons: Currently implemented as W/m² with one person at 24 degreeCelsius and 95 W per persons. 
  *Attention:* Current implementation only says 70 per persons

**Comment by DaJansenGit** [comment]
regarding the persons:
the current calculation doesn't scale with the zone area. What we want to integrate is simple:
person_density: nr of people / m² in zone

this is then scaled with the zone area and used as "NrPeople" in the HumanSensibleHeat_VDI2078 modelica model.

**Comment by PRemmen** [comment]
I'll start to clean up use conditions. My plan is the following and is also related to other issue (#539  #578 #508 #438).

1. I will delete all unused parameters from UseConditions, this should improve usability of the existent ones
2. I will no longer use XML for saving UseConditions in our internal database, but rather use JSON. 
3. I will change to schedules in pandas (I will also integrate some conversion functionalities). however, this means that TEASER will no longer support heating time and the current logic to implement a night set back.

This is going to be a major change and probably will take me some time and also the plan might change will implementing. However I think this is really a good improvement

**Comment by PRemmen** [comment]
I've made some first implementations, one thing that we really should consider is, that we will not be backwards compatible (*.teaserXML) any more without huge effort. this holds especially true for all the parameters that have been loaded withour any use and also because I#m now using UseConditions directly instead of BoundaryConditions (which will be deleted).

**Comment by PRemmen** [comment]
Just that we do not forget about it: moved infiltration_rate from thermal_zone to use_conditions.

**Comment by PRemmen** [comment]
@MichaMans the unit tests for VDI calculation do not work although they work locally. Do you have any idea why?

**Comment by MichaMans** [comment]
@PRemmen could you please be a little bit more specific? Whats the vdi calculation test and what exactly is failing?

**Comment by PRemmen** [comment]
@MichaMans 

https://github.com/RWTH-EBC/TEASER/blob/31adfa7f4109920729e6ea24a82d5e0e7f1f995e/tests/test_data.py#L21
https://github.com/RWTH-EBC/TEASER/blob/31adfa7f4109920729e6ea24a82d5e0e7f1f995e/tests/test_data.py#L46
https://github.com/RWTH-EBC/TEASER/blob/31adfa7f4109920729e6ea24a82d5e0e7f1f995e/tests/test_data.py#L71
https://github.com/RWTH-EBC/TEASER/blob/31adfa7f4109920729e6ea24a82d5e0e7f1f995e/tests/test_data.py#L96

The values for inner walls are failing https://travis-ci.org/RWTH-EBC/TEASER/jobs/526554595#L636 although as said before locally everything is working as expected (tested on Windows and Linux)

**Comment by PRemmen** [comment]
It was actually a stupid mistake. In Python 3.6 onward implemenatation of python dictionary changed (now dictionaries are ordered by default). For other options we need to tell the json encoder to order the entries, see commit: abfff6bf6bbe75c439521990dacbba77212bde17 locally all tests are running for version 2,7 3.4 3.5 3.6 and 3.7 let's see if travis also likes my changes :)
