### ISSUE TITLE
Code Check 

### ISSUE THREAD

**Issue by Stelzhammer** [RWTH-EBC/TEASER#519]
## What is the problem?

- So, 

i ve written a code in TEASER to create a building model and it worked well. But because i need this model for my thesis, i need this model to be validated by someone or someone who can check if the code is right. Like i said, the code works, i can create a model but i need to be sure that the code creates a good model or if there is something i have to change in it. 

thx

Here the Code
[createBuildingFinal1006.txt](https://github.com/RWTH-EBC/TEASER/files/2088253/createBuildingFinal1006.txt)

**Comment by MichaMans** [comment]
@Stelzhammer 
Thank you very much for using TEASER to create Modelica models. In case that this might be a bit disappointing, but we can't validate your model. But here a few suggestions how you can validate you model yourself.
- Create the model and investigate all (or all the relevant) information of your model with a debugger or print statements that might help you to verify your model by yourself
- In case you got measurement data or anything else, you might be able to do a rough validation yourself
- maybe your thesis supervisor could help you with your verification and give you some tips

**Comment by Stelzhammer** [comment]
Hi Michael,

first of all thank you for your quick response.
Unfortunately my superviser has no clue about
Dymola or whatsoever.

But in principle, I can assume that if I use only your templates to
create my model, the model is right ??

Cheers Oleg


Am Mo., 11. Juni 2018 um 08:33 Uhr schrieb Michael Mans <
notifications@github.com>:

**Comment by MichaMans** [comment]
@Stelzhammer ,
sorry that i can't really answer you question, but if the model contains the same information you expect to be there (maybe checked with a debugger, or by viewing the saved project file, etc.) these informations are used for the calculation and then for the export to the modelica files. 
So if thats the case, you'll be fine. But as always, we can't guarantee that there are no bugs.
