### ISSUE TITLE
Support of sunblinds in the thermal zone model

### ISSUE THREAD

**Issue by MichaMans** [RWTH-EBC/TEASER#543]
## What is the problem?

- The advanced model of the aixlib thermal zone supports sunblinds, we should support that

## Why do we want to solve it?

- This enhances the simulation a lot

## How do we want to solve it?

- [x] Check maximum solar irradiation limit when sunblind closes in window class and material type
- [x] Check shading factor if sunblind is closed
- [ ] Integrate both factors in the AixLib Multizone Template

**Comment by MartinRaetz** [comment]
I want to add my conclusion of the present state of the development regarding this sunblind issue:

There are unused parameter in the TypeBuildingElements Json files.
*"shading_max_irr"
*"Shading_g_total"

The WindowElement parameter "shading_max_irr" is not passed on in Teaser.
"Shading_g_total" will be converted to "g_sunblind" but is also not passed on anymore.

In the Modelica AixLib there is then a variable in the "PartialVDI6007" model named "sunblind" which is passed over by the connector and set by a constant source. This "sunblind" parameter reduces the "Equivalent long wave temperature for windows" by the corresponding sunblind factor. Put simply, if sunblind = 1 no long wave radiation penetrates the room, if sunblind = 0 the complete long wave radiation enters the room.

The "sunblind" parameter is statically set to zero, no other value from the database sheets influences it.
Excerpt from Modelicas ThermalZone Class:   
* Modelica.Blocks.Sources.Constant constSunblindWall[zoneParam.nOrientations](each k=0) "Sets sunblind signal to zero (open)";
* Modelica.Blocks.Sources.Constant constSunblindRoof[zoneParam.nOrientationsRoof]
(each k=0) "Sets sunblind signal to zero (open)";

## My suggestions:
1. Delete the values from the TypeBuildingElements Json´s to reduce the complexity and do not mislead the user.
2. Implement the full use of sunblinds. In that case it should be discussed, whether the use of sunblinds should be defined with the used window type (TypeBuildingElements) or with the respective UsageType (UseConditions), or even in another way.

@PRemmen proposed the following 3 step approach:
1. shading_max_irr in die Berechnungen aufnehmen (logic.buildingsobjects.calculation), damit der alle schwellenwerte für alle Fenster und zonen sammelt 
2. Im Modell ThermalZoneEquipped den constanten block (constSunblindWall) durch einen Switch ersetzen der als schwellwert shading_max_irr hat und in eqAirTemp einfließt (hier wird die absortption der kurzwelligen strhalung berechnet)
3. Den output ebenfalls in das Modell corGMod in ThermalZoneEquipped einführen, da dort die transmission der kurzwelligen Strahlung durch das Fenster berücksichtigt wird

**Comment by PRemmen** [comment]
@MartinRaetz I actually solved this issue :) see https://github.com/RWTH-EBC/TEASER/pull/634
