### ISSUE TITLE
AHU profile for durations other than 1 day

### ISSUE THREAD

**Issue by marcusfuchs** [RWTH-EBC/TEASER#553]
## What is the problem?

For an office zone, I would like to specify different volume flow profiles for workdays and for the weekend. Just passing a list of length 7 * 24 to `building.central_ahu.profile_v_flow` does not work, because when `export_aixlib()` calls `modelica_AHU_boundary()`, it runs 

```Python
        if time_line is None:
            time_line = self.create_profile()
``` 

and `create_profile()` uses its default parameters `create_profile(duration_profile=86400, time_step=3600, double=False)`. 

## Why do we want to solve it?

- In my opinion, it would be useful to allow users to specify different AHU operation schedules for periods other than 1 day repeated for the entire year.

## How do we want to solve it?

- I am just playing around with different use_conditions, so it's likely that I am just approaching the problem from a wrong angle.
- If there is no other way already implemented to set AHU operation for workdays and weekends, I suggest to not use the default value of `duration_profile=86400` in `create_profile()` , but instead simply determine the length of  `building.central_ahu.profile_v_flow` and create a corresponding `time_line`.

## Next steps

- If someone (@PRemmen , @MichaMans ?) could provide some feedback whether this is indeed a problem or whether there is a different approach to solving my problem and a solution is needed, I could implement the suggested solution.

**Comment by MichaMans** [comment]
@marcusfuchs currently there is no time_line handling from top level (project) (as far as i know). We currently have the same problem within other project, but we were not able to create a usable solution at the moment. 
But as i see and understand the problem, we might use the current implemented version as default and provide an advanced option for the case you mentioned. It could be:
1. Use the profile from useconditions in hourly resolution and repeat (how to handle different profile lengths for temperature and volume flow etc?)
2. Use some kind of week and weekend definition to create the profiles.

I would suggest 1. but in my opinion the work is a bit under the surface at the handling of different profile lengths and all time_line handling.

**Comment by marcusfuchs** [comment]
@MichaMans Thanks for the fast answer! Before suggesting a solution, I will recap how I see the problem:

From my understanding of the code, the AHU input table is generated from the following 4 variables:

- `profile_temperature`
- `profile_min_relative_humidity`
- `profile_max_relative_humidity`
- `profile_v_flow`

By default, all of them seem to have a length of 24 hours, corresponding to the default `duration_profile=86400` in `create_profile()`.

In my use case, I would like to change `profile_v_flow` to a length of 7 * 24 hours. I would expect typical use cases to 

- specify all 4 profiles to the same length
- specify some profiles on e.g. daily length, others on e.g. weekly length

In my opinion, it would be enough if a solution allowed the user to specify the profile in lengths that always correspond to any number of days (i.e. would not let the user give e.g. a 24 hour profile and a 31 hour profile). With this assumption, I think a solution can be implemented without many other implications. I would suggest to limit the solution to `modelica_AHU_boundary()` by making the following changes:

- Instead of asserting `assert len(time_line) == len(profile_temperature)` etc. after calling `create_profile()` start with asserting that each profile variable has a length that is a multiple of 24
- Determine whether the 4 profiles have the same lengths
  - If they have the same lengths, take that length and pass it on to `create_profile()`
  - Else:
    - Take the longest length as reference
    - Loop all others until they reach the reference length
    - Pass the reference length to `create_profile()`

I may have overlooked something, but in my opinion this would be a solution to the problem. What do you think?

**Comment by MichaMans** [comment]
Yes i think so. I think we already have a first shot in the PR here:
#548 
Maybe we can merge that work into the development as soon as possible. Or you use that as a basis

**Comment by marcusfuchs** [comment]
Thanks for pointing to the PR. This seems like a good start. Yet, for TEASER to allow setting a weekly v_flow profile, it seems like some changes are still necessary. I'll create a branch and propose a solution as outlined above.
