### ISSUE TITLE
Copy weather file to project for increased portability of projects

### ISSUE THREAD

**Issue by marcusfuchs** [RWTH-EBC/TEASER#566]
As I understand the current code, it stores an absolute path to the weather file in the exported building model. We have the use case where we generate models on one machine, but simulate on another machine. Making sure to set the correct absolute path for the weather file over multiple machines has proven to be relatively cumbersome and error-prone in our experience. 

Therefore I suggest the following alternative approach:

- Generate a folder `Resources` within the project export file structure
- Copy a weather file from the given path (or TEASER's default weather file location) to this `Resources` folder
- Use `Modelica.Utilities.Files.loadResource("modelica://...` to load the weather file from the relative project path

For our applications, this would be the preferred standard way of handling weather files in the TEASER exported models. If others agree, I can propose an implementation. An if others prefer the current way, maybe we could add the suggested approach as an option?

**Comment by MichaMans** [comment]
@marcusfuchs thanks for this issue! I like this enhancement. Maybe we should include the boundary condition tables like T_set in the Resource folder as well.

**Comment by marcusfuchs** [comment]
I started looking into this, during which I noticed the following:

The `Project` class documents its `weather_file_path` attribute as follows:

```python
"""
weather_file_path : str
        Absolute path to weather file used for Modelica simulation. Default
        weather file can be find in inputdata/weatherdata.
"""
```

Yet, the `Project.set_default()` function seems to set the default from

```python
self.weather_file_path = utilities.get_full_path(
            os.path.join(
                "data",
                "input",
                "inputdata",
                "weatherdata",
                "DEU_BW_Mannheim_107290_TRY2010_12_Jahr_BBSR.mos"))
```

to 

```python
self.weather_file_path = "modelica://AixLib/Resources/WeatherData/" \
                                 "TRY2010_12_Jahr_Modelica-Library.txt"
```

Even though I suspect from the `TRY2010_12` in both filenames that the contents of the two files should be the same, I think it may be a bit risky to reference two different files here instead of one. As a result of this, the tests in `TEASER/tests/test_data.py` are executed with the second reference via the `MODELICAPATH`. 

To avoid parsing the `MODELICAPATH` in TEASER to copy files, I would propose the following implementation:

- `Project.weather_file_path` accepts both `modelica://...`-paths and absolute paths
- If an absolute path is given, we copy the file to the `Resources` folder, and reference the file in the model via `modelica://...`
- Else the original `modelica://...`-path is used directly in the model without copying

Let me know if you have ideas for a better implementation! 

And I would suggest to consider changing the `set_default` method to not switch to a different weather file, maybe in a separate issue?

**Comment by MichaMans** [comment]
The currently shipped weather file leads to error in the simulation. I think we should change it to a working one

**Comment by MartinRaetz** [comment]
I would like to pick up this topic.

Is there any information about the reason, why the last implementation did not work?

Was the shipped file faulty? Was the implementation faulty?

**Comment by marcusfuchs** [comment]
Sorry, I have no further information after my last post above.

**Comment by MartinRaetz** [comment]
solved in: https://github.com/RWTH-EBC/TEASER/pull/664
