### ISSUE TITLE
SingleFamilyDwelling calculation of est_facade_area with neighbour building

### ISSUE THREAD

**Issue by TobiasBoeth** [RWTH-EBC/TEASER#572]
https://github.com/RWTH-EBC/TEASER/blob/6d18bd8be6bb0bd98a852e0d694c958d33309bc7/teaser/logic/archetypebuildings/bmvbs/singlefamilydwelling.py#L334

The facade area of a single family dwelling is calculated like:

self._est_facade_area = self._est_facade_to_floor_area * \
            self._living_area_per_floor + self._est_extra_floor_area

The value of the attribute _est_extra_floor_area depends on the amount of neighbour buildings. So far so good. But just by the naming of the attributes, isn`t it necessary to put the living area and extra floor area in brackets like:

self._est_facade_area = self._est_facade_to_floor_area * \
            (self._living_area_per_floor + self._est_extra_floor_area)

Otherwise the extra floor area would be summarized in total to the facade area, which doesn't make sense to me!

**Comment by PRemmen** [comment]
You are probably right. This might be a Bug! Could you create a PR?

**Comment by TobiasBoeth** [comment]
Sorry I´m totally new to github. I don`t get it which base to use, neither which comparison to choose for creating a pull request. Don`t want to mess up your organization structure. ;)

**Comment by PRemmen** [comment]
@TobiasBoeth maybe this helps :)

https://github.com/RWTH-EBC/TEASER/wiki/Workflow

https://github.com/RWTH-EBC/TEASER/wiki/Workflow#bugfixes

maybe, you need to create a fork first 👍

**Comment by LauraMaier** [comment]
@TobiasBoeth Are you still working on that bug ? :)

**Comment by XucYin** [comment]
Spontaneously I have made the modification and created a PR. #593

**Comment by XucYin** [comment]
It seems that the values of wall area in test_data.py also need some changes.

**Comment by XucYin** [comment]
This issue is solved in PR #595 together with a version number update.
