### ISSUE TITLE
Individual heating and cooling schedules

### ISSUE THREAD

**Issue by PRemmen** [RWTH-EBC/TEASER#577]
## What is the problem?

- Heating and cooling times and set points can only be specified on a daily basis using `UseConditions` class. 

## Why do we want to solve it?

- I want to specify weekly and maybe even yearly schedules

## How do we want to solve it?

- I will add new attributes and export functions for heating and cooling schedules similar to the occupancy and internal gains schedules. However i'll probably directly switch to something more convenient like pandas

**Comment by MichaMans** [comment]
Also kind of related to #539 #553 #556

**Comment by PRemmen** [comment]
Sorry!!! :(

This is a duplicate!
