### ISSUE TITLE
Should we change schedule inputs to *.txt

### ISSUE THREAD

**Issue by PRemmen** [RWTH-EBC/TEASER#578]
## What is the problem?

- Currently all schedules are exported as *.mat files. This makes manipulation after export quite difficult

## Why do we want to solve it?

- To manipulate schedules more easily

## How do we want to solve it?

- change export from *.mat to *.txt

any objectsion @MichaMans

**Comment by MichaMans** [comment]
@PRemmen no objections from my side, but i would keep both ?!

**Comment by marcusfuchs** [comment]
Just throwing in my opinion: I think moving to TXT would be a huge improvement for us (and we would not need to keep MAT)

**Comment by PRemmen** [comment]
I'll try to work on it in the next time
