### ISSUE TITLE
Drop Python 2 support

### ISSUE THREAD

**Issue by marcusfuchs** [RWTH-EBC/TEASER#585]
The clock is ticking: https://pythonclock.org/

In order to make development easier, I would suggest to stop testing for and supporting Python 2 as soon as possible. I would even go further and drop support for anything < 3.6 . It's an easy simplification of the development process and I would expect this to not affect any users?

My ideal outcome of this issue would be to drop support for anything below Python 3.6 immediately. If this is not possible, could we at least have a plan on when to stop supporting Python 2?

**Comment by MichaMans** [comment]
@marcusfuchs i think we currently have no roadmap for a python 2 exit strategy, especially no timeline. But why not using the clock you posted 😃
As you question/suggestion is quite out of context, its hard for me to really rate it. I think at the moment the current overhead for supporting python 2 and <3.6 is not that much. BUT i took a look at https://www.jetbrains.com/research/python-developers-survey-2018/ and it seems, that the actual py2 community is really small (where in the release year of teaser, it actually was in advance of py2 vs py3).

As long as we have no real case were py2 is a barrier, we should support till clock stops

**Comment by marcusfuchs** [comment]
Here is an example: In #570 the tests work for Python 3, but not 2 (see https://travis-ci.org/RWTH-EBC/TEASER/builds/521159522?utm_source=github_status&utm_medium=notification). Should we really spent energy on fixing the tests for Python 2? In addition, I think it would be nice to not have all these `future` imports that cause a warning in IDEs about version conflict. And furthermore, if we could focus on modern concepts like f-strings I think the code base would increase in quality and productivity.

**Comment by MichaMans** [comment]
I agree. Lets drop it, if @PRemmen agrees

**Comment by mlauster** [comment]
I'm also still available! :) I'm fine with dropping

**Comment by PRemmen** [comment]
Totally fine with it.

I would also prefer dropping everything below 3.6 (see my issues with python below python 3.6 #510 ).

**Comment by marcusfuchs** [comment]
Great, I'm happy about the fast agreement and created a PR.
