### ISSUE TITLE
Code formatting

### ISSUE THREAD

**Issue by PRemmen** [RWTH-EBC/TEASER#587]
## What is the problem?

- current developers are using different linter tools to format code (we have been using linter-flake8, others are using black @marcusfuchs, @miraschmid)
- I have no strong feelings about what to use (we can move to black)
- However, black uses 88 characters per line we need to agree on the same settings

## Why do we want to solve it?

- to not have a lot of overhead because of different code formatting in commits

## How do we want to solve it?

- @marcusfuchs @miraschmid can I ask you to send us your settings for black so we can use the same?

**Comment by marcusfuchs** [comment]
In order to avoid any confusion and have the most simple setup, we use black as it comes out of the box without changing any settings, i.e. also using the 88 characters by default.
