### ISSUE TITLE
IdealHeaterCooler Outside temperature controlled

### ISSUE THREAD

**Issue by DaJansenGit** [RWTH-EBC/TEASER#588]
With the integration of https://github.com/RWTH-EBC/AixLib/pull/732 into AixLib we have a controller that sets the ideal heater cooler active or unactive by taking the outside air temperature into account. For TEASER we need to integrate some parameters for export to parameterize the controller. 
This will be:

- _zoneParam.use_conditions.T_threshold_IdealCooler_ Threshold temperature for cooling (default should be 24 °C)
- _zoneParam.use_conditions.T_threshold_IdealHeater_ Threshold temperature for heating (default should be 15 °C) 
- _zoneParam.use_conditions.IdealHeaterCoolerThresholdControlled_ Should controller be used: if yes: controller will be used and "statorDyn" will be set false for the heatercoolerPI

**Comment by PRemmen** [comment]
probably related to #617 and #618
