### ISSUE TITLE
Renaming: alpha becomes hConv and hRad

### ISSUE THREAD

**Issue by PMehrfeld** [RWTH-EBC/TEASER#590]
@MichaMans: As bespoken:

Related...
- Issue: https://github.com/RWTH-EBC/AixLib/issues/711
- PR: https://github.com/RWTH-EBC/AixLib/pull/723
- comment: https://github.com/RWTH-EBC/AixLib/pull/723#discussion_r299473444

**Comment by MichaMans** [comment]
as https://github.com/RWTH-EBC/AixLib/pull/723 got merged, we should fix the naming in the teaser dev asap

**Comment by PMehrfeld** [comment]
@MichaMans: If the merges solved the issue, this one can be closed.
