### ISSUE TITLE
Inconsistent version number in tags

### ISSUE THREAD

**Issue by XucYin** [RWTH-EBC/TEASER#597]
## What is the problem?

The tag number of the current release ([view tags](https://help.github.com/en/articles/viewing-your-repositorys-tags)) is one step back as the version number in README.md, setup.py and doc/conf.py (probably since tag [v0.6.7](https://github.com/RWTH-EBC/TEASER/tree/v0.6.7)).

## How do we want to solve it?

I'm not sure if I'm the right person to manage the releases. It would be appreciated if someone with the authorization could take a look.

**Comment by MichaMans** [comment]
@XucYin Seems that we forgot to draft a new release once. However i updated the actual one to 0.6.9 so it should be fine now. Please close this, if you agree.

**Comment by XucYin** [comment]
@MichaMans Thank you for the rapid editing! Now it looks good. So I close this issue.
