### ISSUE TITLE
Building data import script

### ISSUE THREAD

**Issue by MartinRaetz** [RWTH-EBC/TEASER#599]
## What is the problem?

-  It´s tedious to implement each wall segment by hand. An automated import script is desired.

## Why do we want to solve it?

- 

## How do we want to solve it?

- With an import script. This script will import building data from an Excel file and initiate the respective zones, walls, windows, etc. in Teaser. Some additional parameters are imported as well. Additional parameters can be added at any time.

**Comment by MichaMans** [comment]
@MartinRaetz I like that! We can think about an implementation in the example section.

**Comment by MartinRaetz** [comment]
@MichaMans would you think this "Tool" should be part of Teaser or rather referenced in Teaser and maintained in another repository?

If it should be in Teaser, I thought about adding a new folder named "import scripts" or similar, where all kind of import methods can be collected, e.g. the CityGML import of @PRemmen. You may have a look at the branch and let me know about the desired structure.

**Comment by MichaMans** [comment]
@MartinRaetz maybe a few comments:

I would rather see this as an example then an import script. Reasons for me personally are, that if we support some kind of import of other formats natively, we should implement that in the project or something like this, but i am not sure if we want support an excel import natively. Thus, i follow that we first implement that as an example and also provide the excel file in examples, that other users can use that as their starting information. Nevertheless, i'm open for a native teaser implementation. 
But lets wait for the thoughts from @PRemmen

**Comment by MartinRaetz** [comment]
@MichaMans I agree with you.

**Comment by PRemmen** [comment]
I'm also in favor of an example. TEASER was actually "designed" to easily interface to lots of different data formats (like you mentioned citygml, databases, ...). As EXCEL is a common tool we can provide a nice example but I would not implement it in the workflow of TEASER. This typically means a lot of maintanence work, e.g. if something changes in the strucutre of TEASER, an example is fixed more easily.

so: go ahed :)
