### ISSUE TITLE
[Question] Running simulation Examples what is wrong?

### ISSUE THREAD

**Issue by AmeCode** [RWTH-EBC/TEASER#601]
1. When I ran TEASER\teaser\examples\e2_export_aixlib_models.py in python and open TEASEROutput\ArchetypeExample\Package.mo with Dymola and click simulate on any of the objects under ArchetypeExample (ResidentialBuildingTabula) I get the following result:
[https://ibb.co/6t5cJdz](url)
[https://ibb.co/qJ8SH1y](url)
2. When I ran TEASER\teaser\examples\e3_export_ibpsa_models.py in python and open any of the TEASEROutput\ArchetypeExample\Package.mo with Dymola and click simulate I get the following result: 
[https://ibb.co/m424pRf](url)
[https://ibb.co/YtnrBXf](url)
3.  When I ran TEASER\teaser\examples\simulation\singlebuilding_simulation.py in python and open simulator.log in TestCampusSimulation\simulator.log I get the following text:
[https://ibb.co/WPvQz6q](url)
Can you help me to see a working simulation result from Teaser example?
Any help would be appreciated as I am completely new to TEASER and Building SImulations

**Comment by mlauster** [comment]
@AmeCode, your links does not seem to work, at least for me. You can upload images directly to github.

**Comment by MichaMans** [comment]
@AmeCode i think you figured it out in the meantime. (discussion via email) Please reopen the issue if you facing some problems again.

**Comment by AmeCode** [comment]
If anybody can at least run the output from the third example: e3_export_ibpsa_models.py (which seems to be good to run with OpenModelica or Dymola or JModelica) with OpenModelica, as I now need them to run with OpenModelica (or any other free licence software as it is part of my thesis), please provide me with the way of doing so as I keep getting errors with OpenModelica v1.14.0, TEASER 0.6.9 and AixLib 0.7.4:
[https://docs.google.com/document/d/1cBKHPmRkUhChhKDEK0Py2kBUiaTCl03ZhZBibt1C_aA/edit?usp=sharing](https://docs.google.com/document/d/1cBKHPmRkUhChhKDEK0Py2kBUiaTCl03ZhZBibt1C_aA/edit?usp=sharing).
and I have also tried other libraries for e3_export_ibpsa_models.py , like Buildings, IDEAS and buildingsystems without success.
