### ISSUE TITLE
[Questition] How can I supply the internal gains from a .mat file and not use the default

### ISSUE THREAD

**Issue by AmeCode** [RWTH-EBC/TEASER#603]
Hi all,
I have used the multizone model, which takes WeaData, Internal Gains, T_set and a constant as an input. I generated the model for Dymola using the second example provided in TEASER(http://rwth-ebc.github.io/TEASER/teaser_api_example.html#example-2-export-modelica-models-for-aixlib-library-using-teaser-api) and the weather data is added by prj.weather_file_path(), but how can I add the internal gains file manually and not use the one generated by TEASER?
Greetings,
Ahmed

**Comment by MichaMans** [comment]
@AmeCode if you have already prepared your own mat file, you can simply change it in the Modelica Model. The CombiTimeTable is able to load your mat file if you change the path to your own file in that model.

**Comment by AmeCode** [comment]
Thanks @MichaMans for your quick reply. But I need a way to change it from TEASER directly like the way I can add my own weather file using prj.weather_file_path(), without opening Modelica.

**Comment by mlauster** [comment]
Then name your .mat file like in Teaser and replace the generated ones by your own in the subsequent folders. If you need this done automatically, write a python script for this task.

**Comment by PRemmen** [comment]
Just adding my 2 cents: Best option would not to use a manually created file but to change the time series for internal gains in the corresponding use_conditions of the thermal zones. This has become a lot easier in current development branch
