### ISSUE TITLE
Prepare next release

### ISSUE THREAD

**Issue by PRemmen** [RWTH-EBC/TEASER#604]
## What is the problem?

- We haven't released a new version for quite some time, but there have been a lot improvements that are already in branch

## Why do we want to solve it?

- To provide users the new nice features of TEASER

## How do we want to solve it?

- Define what kind of issues needs to be solved for next release and then merge development into master. @MichaMans any suggestions on issues?

**Comment by PRemmen** [comment]
I suggest that @PRemmen  solves #602 before new release ;-)

**Comment by MichaMans** [comment]
I think we also need to check with @DaJansenGit, @KremerMartin  and @MartinRaetz how their progress is and if there is something we need to consider 😃

**Comment by DaJansenGit** [comment]
#567 is still ongoing, we need someone to recalc everything from SIA to person/m2 and insert the data into the .json files. Maybe one of you has some hiwi capacities to do this? :) @PRemmen @MichaMans @KremerMartin @MartinRaetz

**Comment by DaJansenGit** [comment]
We want to release a new version of AixLib as well with https://github.com/RWTH-EBC/AixLib/milestone/5 
Since we have non backward compatible changes in both, AixLib and TEASer, we should try to do this together so that the current realeases work together

**Comment by KremerMartin** [comment]
@PRemmen @MichaMans @MartinRaetz 
My Hiwi will prepare the necessary implementations into the .json files. @DaJansenGit will instruct him what to do.

**Comment by PRemmen** [comment]
@KremerMartin @DaJansenGit Nice! :) it should not be very hard to do it (as it is json! 👍 ) If you need any help I can help. 

Releasing new versions of aixlib and teaser at the same time is a very nice idea! :) is 20th semptember a fixed date?

**Comment by PRemmen** [comment]
https://github.com/RWTH-EBC/TEASER/commit/4e9b297601bd0c3e0a00d9051aa31b05ff0a03e2
