### ISSUE TITLE
[Question] How is the parameter calculated

### ISSUE THREAD

**Issue by AmeCode** [RWTH-EBC/TEASER#606]
Hi there,
I managed to run the modelica model generated by TEASER using Dymola. There is a parameter, which I try to compare with its counterpart from another methodology (other than TEASER). I am looking for the parameter which stands for the total required heat energy of the building and
I think that parameter is multizone.PHeater[1].
How is this parameter calculated or which are the main parameters that affect this parameter? Is there any equation behind it? 
If anybody knows the answer or can tell me how to figure it out, please help me.
Greetings,
Ahmed

**Comment by MichaMans** [comment]
@AmeCode I'm not really sure what you are looking for, but the PHeater value is the heating power provided by an ideal heater, controller via a idealized (at least that's the indention) PI Controller, to achieve the set point temperatures for the thermal zone in the building.

**Comment by AmeCode** [comment]
Thanks @MichaMans, What am I looking for are the factors changing PHeater value, for example heat flow due to ventilation losses or heat flow due to solar radiation any other factor which may change the PHeater values.
