### ISSUE TITLE
[Question] how to calculate ventilation heat losses?

### ISSUE THREAD

**Issue by AmeCode** [RWTH-EBC/TEASER#607]
Hi there,
I need a way to calculate the heat losses due to Ventilation in TEASER. Is there a parameter which indicates Q_flow due to ventilation/infiltration ? 
Any help would be appreciated.
Greetings,
Ahmed Amer

**Comment by MichaMans** [comment]
@AmeCode If I understand that right, you can find these values in the Ventilation and Infiltration area in the ThermalZone. Hope that helps. The heat transfer there should be related to ventilation and infiltration heat transfers.
![image](https://user-images.githubusercontent.com/15192234/66289613-76334a00-e8dd-11e9-9c9d-0d1c886dce15.png)

If you are looking for a parameter to change the infiltration and ventilation, you can have a look at the current documentation of TEASER http://rwth-ebc.github.io/TEASER/ there the you can use also the search function to find parameters like infiltration_rate. Hope that helps.

**Comment by AmeCode** [comment]
Thanks @MichaMans it has helped me a lot :)
