### ISSUE TITLE
Add a dev-channel to the automated deployment to PyPI

### ISSUE THREAD

**Issue by marcusfuchs** [RWTH-EBC/TEASER#613]
## What is the problem?

As discussed with @PRemmen , we think it would be great to auto-deploy TEASER's development branch to PyPI. Currently, PyPI serves all releases made from TEASER's master branch. Yet, many improvements stay in the development branch between releases. Therefore users (and CI-Pipelines) need to manually clone, checkout the development branch and manually install the local copy of TEASER to get the latest improvements.

## Why do we want to solve it?

Allowing e.g. `pip install teaser-dev` instead of having to clone and switch to the development branch in order to get the latest and greatest TEASER would significantly simplify our workflows using TEASER. 

## How do we want to solve it?

- I think it could be possible to add an auto-deployment to TEASER'S CI/CD pipelines which publishes the development branch onto PyPI e.g. to `teaser-dev` without major effort.
- Alternatively, one could think about not using a development branch and releasing each PR with merging directly to the master branch, but I would expect that this would require more effort and may not be desired by the core developers

**Comment by MichaMans** [comment]
@marcusfuchs 
Thanks for this idea!
I would definitively stay with a development branch. So option 1 would be the only one I could vote for. 

But maybe a more general thought. Would it really be more effortless then just installing the development version with pip, directly from github?
e.g.
```
pip install --upgrade git+https://github.com/RWTH-EBC/TEASER@development
```

**Comment by marcusfuchs** [comment]
@MichaMans Thank you so much for this information. I was not aware that pip can install from the repo like this - I thought only packaged installations from PyPI were possible. Your solution solves our use case perfectly, so I'm closing this. Thanks again!
