### ISSUE TITLE
Which are valid attributes of project.retrofit_all_buildings()?

### ISSUE THREAD

**Issue by maxmegaman** [RWTH-EBC/TEASER#619]
Dear TEASER-Team,

Is it possible to find valid values of all attributes in project.retrofit_all_buildings()?
Regarding to the documentation, the doctrings and the provided example 6 the following attributes can be set:
- year_of_retrofit = [`1995 <= year_of_retrofit <= 2015`], 
- type_of_retrofit = [`retrofit`, `adv_retrofit`]
- window_type = [`Alu- oder Stahlfenster, Isolierverglasung`, ???]
- material = [`EPS_perimeter_insulation_top_layer`, ???]

My question is related to window_type and material attributes. Which other keywords can be used and where can I find these keywords?
Besides this I am wondering if it is possible to get the thickens of the added insulation layer and the EPS-value somehow? Especially for the usage of iwu`/`bmvbs` archetypes. The documentation just says: "The thickness of the insulation layer is calculated that the U-Value of the wall corresponds to the retrofit standard of the year of retrofit".

Thank you in advance for any help and regards.

**Comment by MichaMans** [comment]
@maxmegaman

**Comment by maxmegaman** [comment]
Thanks a lot for your quick reply.

I was looking for a solution for IWU archetypes. Sorry for not mention it before.
The solution you provided worked out to find the thickness of the outer layer. Also other data, e.g. conductivity, capacity and area, could be extracted in the same way. 
Furthermore, it helped a lot to use the debugger mode of a Python IDE to check all available parameters and variables in teaser. 

For further use of teaser I suggest to publish an overview of the used hierarchical structure in TEASER. That might ease the usage of TEASER for other users in future.

But thanks a lot for all the effort you put into TEASER. It is a great tool and we are very happy to use it.
