### ISSUE TITLE
Update version number in teaser.logic.calculation

### ISSUE THREAD

**Issue by PRemmen** [RWTH-EBC/TEASER#627]
## What is the problem?

- A quite stupid mistake :( with the latest release we haven't updated the AixLib version numbers, which will result in non functional Modelica models

## Why do we want to solve it?

- to run modelica simulation

## How do we want to solve it?

- increase version number and also increase version number of TEASER 0.9.1.

**Comment by DaJansenGit** [comment]
With https://github.com/RWTH-EBC/AixLib/pull/856 we needed to raise the AixLib version to v0.9.1 thus we need to raise it in TEASER as well.
