### ISSUE TITLE
inner IR emissivity calculation

### ISSUE THREAD

**Issue by PGorzalka** [RWTH-EBC/TEASER#639]
Hi guys,

I stumbled across weird IR emissivity values, so I thought I'd take the opportunity to create my first GitHub issue. As I usually don't work with GitHub, I don't really now the usual workflow. Hope this is the right thing to do :)

## What is the problem?

- Inner IR emissivity values become very high (>> 1)
- equations in [TEASER/teaser/logic/buildingobjects/calculation](TEASER/teaser/logic/buildingobjects/calculation) seem to be wrong. Examples (there are other similar lines):
  - [three_element](TEASER/teaser/logic/buildingobjects/calculation/three_element.py) line 791-797

     `self.ir_emissivity_inner_iw = (
            sum(in_wall.layer[0].material.ir_emissivity * in_wall.area for
                in_wall in self.thermal_zone.inner_walls)
            + sum(floor.layer[0].material.ir_emissivity * floor.area for
                  floor in self.thermal_zone.floors)
            + sum(ceiling.layer[0].material.ir_emissivity * ceiling.area for
                  ceiling in self.thermal_zone.ceilings) / self.area_iw)`

     should be

     `        self.ir_emissivity_inner_iw = ((
            sum(in_wall.layer[0].material.ir_emissivity * in_wall.area for
                in_wall in self.thermal_zone.inner_walls)
            + sum(floor.layer[0].material.ir_emissivity * floor.area for
                  floor in self.thermal_zone.floors)
            + sum(ceiling.layer[0].material.ir_emissivity * ceiling.area for
                  ceiling in self.thermal_zone.ceilings) / self.area_iw`

  - [four_element](TEASER/teaser/logic/buildingobjects/calculation/four_element.py) line 759-761

     `        self.ir_emissivity_inner_ow = (
            (sum(out_wall.layer[0].material.ir_emissivity * out_wall.area for
                 out_wall in self.thermal_zone.outer_walls)))`

     should be

     `        self.ir_emissivity_inner_ow = (
            (sum(out_wall.layer[0].material.ir_emissivity * out_wall.area for
                 out_wall in self.thermal_zone.outer_walls)) / self.area_ow)`

## Why do we want to solve it?

- I think the values are not needed for export, but wrong equations should be corrected anyway. Sorry if I got something wrong and these are intentional values ;)

## How do we want to solve it?

- Have a look at all IR emissivity equations in the calculation folder and correct them if necessary

**Comment by PRemmen** [comment]
HI @PGorzalka,

sorry for late answer, I am afraid I overlooked this issue. You seem to be right, thanks for the catch! The equations are not directly needed for export, however they should be considered in the lumped RC-Values for 3, and 4 Element models (I almost never use them so I cannot tell how big the impact is).

If you would like to contribute to TEASER it would be nice if you could fix this issue and create a PR :+1: .  To do that you need to create a fork (https://help.github.com/en/github/getting-started-with-github/fork-a-repo) and from that fork create a PR in this repository, this will then get merged into master (https://github.com/RWTH-EBC/TEASER/wiki/Workflow#bugfixes) - you do not need to care about PIP release

**Comment by PGorzalka** [comment]
Hi @PRemmen,

no worries, I already assumed so :) I'll fix this as soon as I have time, probably within the next 2 weeks.
