### ISSUE TITLE
Default shading significantly changes model results

### ISSUE THREAD

**Issue by marcusfuchs** [RWTH-EBC/TEASER#653]
When we simulate our reference buildings with the most recent TEASER development version and AixLib development version, the results are significantly different. It seems like the heat demand is increased by roughly a factor of 2 while the cooling demand is significantly reduced. This seems to be caused by the fact that with the same settings, the solar radiation (`ROM.solRad`) is reduced to 0 for the entire year for 4 orientations. I am not sure whether this can be interpreted as no irradiation on all 4 walls' windows. Previously, the heating power and the radiation for one example building (residential) looked like this:

![image](https://user-images.githubusercontent.com/5516900/83256398-a4d69b80-a1b2-11ea-857f-74eaaa83cb54.png)

With the new version, things change to this:

![image](https://user-images.githubusercontent.com/5516900/83256428-b61fa800-a1b2-11ea-889a-881d3483358d.png)

Just wanted to check to ask

- does this mean that by default, all windows are completely shut for the entire year and no solar gains reach the interior of the building?
- is this the intended behavior for the recent changes?

Any help for clarifying this is greatly appreciated! Thanks in advance!

**Comment by marcusfuchs** [comment]
I am still not familiar enough with this part of TEASER, but this seems to be related to the fact that all Tabula settings include these data:

```
"shading_g_total": 0.0,
"shading_max_irr": 0.0,
```

When setting  `"shading_g_total": 1.0,` I can reproduce our old results.

**Comment by MartinRaetz** [comment]
Hello @marcusfuchs, 
and thank you for checking this out.

A g-value of 1.0 represents full transmittance of all solar radiation while 0.0 represents a window with no solar energy transmittance. Hence, the g-value of the shading should be 1 for "no shading" and 0 for  "full shading". The previous implementation in the AixLib did a double (1-g_value) conversion. We made this more straight forward with the recent changes.
Sunblinds weren´t applicable in the previous version. 

Just as you found, you will need to set the g_value of the shading to 1 if you do not want to consider sunblinds.

Do we need to adjust default values in the Tabula settings?

**Comment by PRemmen** [comment]
@MartinRaetz Yes, that would be a good idea. I think shading default value should always be 1.0 (i. e. no shading)

**Comment by MartinRaetz** [comment]
@marcusfuchs would you volunteer to change the respective parameters?

**Comment by marcusfuchs** [comment]
Thanks for the answers and the explanation of the changes.

Regarding the default values, I would consider it an improvement to change this. In my opinion the current defaults are not good choices because closed blinds for the entire year are not what I think users would expect as default. 

Regarding the changes in the shading, it seems like you use 2 different approaches to naming. Teaser internally seems to use `"shading_g_total"`, while the Modelica model and the record outputted by TEASER uses `shadingFactor`. While I have no objections to 

> the g-value of the shading should be 1 for "no shading" and 0 for "full shading"

I think that a "shading factor" of 1 meaning no shading and a "shading factor" of 0 meaning full shading is a bit confusing. From the name "shading factor", I would expect that 1 would rather mean 100 % shading and 0 meaning 0 % shading. So I can understand why there was a double conversion. But I can also live with the new implementation if you prefer to keep it that way.

And regarding volunteering unfortunately I have currently no bandwidth available to fix this quickly and as we have already implemented an internal solution to keep our nightly tests running this is also not urgent for me. So I would be grateful if this can be taken up by someone else, but if it's not fixed when I have time I am of course open to pick this up later.

**Comment by MartinRaetz** [comment]
I think this issue is solved, feel free to reopen it if that is not the case.
