### ISSUE TITLE
Weatherdata "real" export (not link)

### ISSUE THREAD

**Issue by MartinRaetz** [RWTH-EBC/TEASER#655]
## What is the problem?

- Teaser does not export weather data, it only links the repo where the weather data is stored at the pc of the Teaser instance.

## Why do we want to solve it?

- If Teaser exports also the weather data, the exported model could be easily distributed among different pc´s. 

## How do we want to solve it?

- Export the weather file just like the other data (useconditions, etc.)

![grafik](https://user-images.githubusercontent.com/28930877/83785578-cd1e3880-a691-11ea-8175-a56204ff9f0f.png)

**Comment by marcusfuchs** [comment]
@MartinRaetz This may be a duplicate of #566? Unfortunately I had no time to work on that, but I would of course welcome any change in this direction.

**Comment by MartinRaetz** [comment]
@marcusfuchs thank you for notifying! You are right, I will close this duplicate.
