### ISSUE TITLE
Enable regression testing of TEASER output with BuildingsPy

### ISSUE THREAD

**Issue by marcusfuchs** [RWTH-EBC/TEASER#669]
For quality control, I think it would be really useful if we could easily run all models generated from a TEASER project as regression tests. With BuildingsPy this can be achieved fairly easy. As TEASER outputs a Modelica package, all that is need for this is to add the following things to the output:

- Add a script e.g. `/Resources/Scripts/runUnitTests.py` similar to https://github.com/RWTH-EBC/AixLib/blob/development/bin/02_CITests/UnitTests/runUnitTests.py
- Add annotations to each building model that enable using the model as a regression test
- Add MOS scripts to run the regression tests as in https://github.com/RWTH-EBC/AixLib/tree/development/AixLib/Resources/Scripts/Dymola

This way, BuildingsPy can directly run the simulation of all buildings as a regression test and generate reference results. Then users can always verify whether the models still give the same results.

I can suggest an implementation for this, but feedback and help is of course very welcome

**Comment by MichaMans** [comment]
@marcusfuchs I like this addition! I may check an automated testing in the CI afterwards. 👍

**Comment by marcusfuchs** [comment]
@MichaMans Yes, I think this would be perfect. We already have implemented something similar as would be needed for TEASER, so once I get around to work on this I think the effort required will not be too large. For automated testing in your CI afterwards, I also think that https://github.com/lbl-srg/BuildingsPy/issues/393 will be helpful so you do not have to copy the reference results into the output directory.

**Comment by marcusfuchs** [comment]
@MichaMans Starting to use this I noticed one error: I forgot to add the `modelica_test_script` template to `setup.py`, so when installing TEASER from GitHub with `pip install --upgrade git+https://github.com/RWTH-EBC/TEASER@development` the file is missing. I'll create a PR to fix this.

**Comment by marcusfuchs** [comment]
@MichaMans Thanks again, this is all working as intended, so I am closing this.
