### ISSUE TITLE
Dev to Master (due to AixLib update)

### ISSUE THREAD

**Issue by MartinRaetz** [RWTH-EBC/TEASER#688]
## What is the problem?

- The AixLib Master is updated with the development. Current Teaser master is not anymore compatible with AixLib master.

## Why do we want to solve it?

- Restore compatibility

## How do we want to solve it?

- Merge Teaser development into Master

**Comment by MartinRaetz** [comment]
Manually tested files:

- [ ] verification_ASHRAE_140_600.py
- [ ] verification_ASHRAE_140_620.py
- [ ] verification_ASHRAE_140_900.py
- [ ] verification_ASHRAE_140_920.py
- [ ] e2_export_aixlib_models.py
- [ ] e6_generate_building.py (including AixLib export)
- [ ] e9_building_data_import_from_excel.py

**Comment by MichaMans** [comment]
@MartinRaetz 
As far as I can see is this merge done, right? Unfortunately the auto deployment to pypi seems to be not existing anymore (as we are not using travis anymore?) We should change that and introduce a new github action for this deployment. Do you agree?

**Comment by MartinRaetz** [comment]
Thank you for noticing! 
I agree with you!
