### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by MartinRaetz** [RWTH-EBC/TEASER#701]
## What is the problem?

- Documentation seems to be out of date
- [http://rwth-ebc.github.io/TEASER/index.html](http://rwth-ebc.github.io/TEASER/index.html) is for Version 0.6.0

## Why do we want to solve it?

- A good documentation does help new users.

## How do we want to solve it?

- Agree on a way how to document
- Update [http://rwth-ebc.github.io/TEASER/index.html](http://rwth-ebc.github.io/TEASER/index.html) ?
- New users should pinpoint critical aspects which are missing in the documention.

**Comment by DaJansenGit** [comment]
Hey, thanks for opening the issue :) I totally agree that we need to update our documentation. As the TEASER documentation is build via Sphinx and we already have a CI template to integrate the sphinx doc building via CI we should use it here.

Link (only internal): https://git-ce.rwth-aachen.de/ebc/ebc-general/templates/gitlab-ci/-/tree/master/python/doc

**Comment by DaJansenGit** [comment]
will be solved by this: https://github.com/RWTH-EBC/TEASER/issues/738

**Comment by FWuellhorst** [comment]
This was closed by #740
