### ISSUE TITLE
Danish tabula archetypes

### ISSUE THREAD

**Issue by amaccarini** [RWTH-EBC/TEASER#724]
Hi,
Some year ago I developed a piece of TEASER code to enable calculation of Danish Tabula archetypes. I just tried to run the code and I got some errors when exporting the models. As an example, I simply tried to replace the string `tabula_de` with `tabula_dk` in line 100 of file _e1_generate_archetype.py_ and then run the file _e3_export_ibpsa_models_. I got some errors that I cannot debug. Hope you can help.

**Comment by DaJansenGit** [comment]
This seems obsolete, if there is still help needed, please reopen the issue.
