### ISSUE TITLE
Add illuminance levels and lighting efficiencies in use-conditions

### ISSUE THREAD

**Issue by HoeppJ** [RWTH-EBC/TEASER#753]
## What is the problem?

- At the moment, internal lighting gains are only based on the input of fixed electrical lighting power per zone [W/m²] in the use conditions.

## Why do we want to solve it?

- In standards for usage boundary conditions of buildings (e.g. DIN V 18599-10, SIA 2024) only the illuminance level [lx = lm/m²] for specific zones is defined. 
- The electrical lighting power can then be determined using the lighting efficiency [lm/W] which depends on the used lighting device (halogen, LED, etc.)

## How do we want to solve it?

- Additional getter and setter methods are added in the useconditions.py class, so that the electrical lighting power per zone is determined by one of two options:
1) Fixed input of the electrical lighting power per zone in the use-conditions
2) Calculation of the electrical lighting power per zone by the input of an illuminance level and lighting efficienciy per zone in the use-conditions
- By adding a boolean variable, it will be possible to switch between these two options.
- Option 1) will be selected as default

**Comment by DaJansenGit** [comment]
closed by #763
