### ISSUE TITLE
How to run files after instruction

### ISSUE THREAD

**Issue by Betterbuilt00** [RWTH-EBC/TEASER#755]
> Just stopping by to let us know about some issue you encountered with TEASER? Please feel free to delete all of this text and tell us what you think!

> If you want to suggest larger changes and/or adding new features to TEASER, please make sure to briefly answer the following few questions. For more information on how to contribute to TEASER, see our [Wiki](https://github.com/RWTH-EBC/TEASER/wiki). Before submitting the issue, you can delete these first lines. Thanks for contributing!

## What is the problem?
1. I generated Modelica files following the guidelines in the TEASER manual, but there were no instructions on how to run them.
2. When I tried to open these files using OpenModelica separately, I encountered various errors. For example, the recent error message was "[Translation Error: [ArchetypeExampleIBPSA.ResidentialBuilding.ResidentialBuilding_Models.ResidentialBuilding_SingleDwelling: 16:10-16:32]: Modified element lat not found in class DiffusePerez]."
- ...

## Why do we want to solve it?

- ...

## How do we want to solve it?

- ...

**Comment by FWuellhorst** [comment]
@Betterbuilt00 , sorry for this late fix. We did not look into the IBPSA export for quite some time, as we typically only use AixLib. However, we fixed it in a new PR
