### ISSUE TITLE
Create Typebuilding from loaded xml data

### ISSUE THREAD

**Issue by MichaMans** [RWTH-EBC/TEASER#93]
I think a good enhancement is to allow the user to use the loaded xml data to create a new typebuilding.
For example if a user uses a simple xml with only the basic building data in it, we should support that the user can create any typebuilding he wants from the loaded data.

Therefore we need to figure out what's the best implementation here. If we adopt the given building data in the createTypeBuilding-Window, we need to make sure that the user can choose if he wants to create a new building, or if he wants to change the current building. 

What do you think?

**Comment by yGoerguelue** [comment]
Found two bugs.
- It doesnt matter if we click on the construction type light, because it is automatically set to heavy in our    building object. 
- If we generated a building of a Office type and press the fill current information button the construction type is not set.

**Comment by MichaMans** [comment]
merged with #289
